trigger:
  branches:
    include:
      - main
  paths:
    include:
      - rabbitmq/*
      - UpdateContact/UpdateContact.Worker/*

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: $(_dockerRegistryServiceConnection)
  imageRepository: $(_imageRepository)
  containerRegistry: $(_containerRegistry)
  dockerfilePath: $(_dockerfilePath)

  k8s-deployment: $(_k8s-deployment)
  k8sPathName: 'rabbitmq/deployment.yaml'
  kubernetesServiceEndpoint: $(_kubernetesServiceEndpoint)
  kubernetesNamespace: $(_k8sNamespace)
  tag: '$(Build.BuildId)'

  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo Show ws files.
          echo $(ls)
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        buildContext: $(System.DefaultWorkingDirectory)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest

  - job: UploadArtifact
    displayName: "Upload Deployment YAML"
    dependsOn: Build
    steps:
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/$(k8sPathName)
        artifact: $(k8s-deployment)
        publishLocation: 'pipeline'

- stage: Deploy
  displayName: Deploy Stage
  jobs:
  - job: DeployDatabase
    displayName: Deploy to AKS
    steps:
      - script: ls $(System.DefaultWorkingDirectory)/k8s
        displayName: "Check folder $(System.DefaultWorkingDirectory)"
      - script:  |
          cat $(System.DefaultWorkingDirectory)/sql-server/k8s.dev.yaml
          sed -i 's/PLACEHOLDER_NAMESPACE/$(kubernetesNamespace)/g' $(System.DefaultWorkingDirectory)/$(k8sPathName)
          sed -i 's/PLACEHOLDER_CONTAINER_REGISTRY/$(containerRegistry)/g' $(System.DefaultWorkingDirectory)/$(k8sPathName)
          sed -i 's/PLACEHOLDER_IMAGE_REPOSITORY/$(imageRepository)/g' $(System.DefaultWorkingDirectory)/$(k8sPathName)
          sed -i 's/PLACEHOLDER_TAG/$(tag)/g' $(System.DefaultWorkingDirectory)/$(k8sPathName)
        displayName: 'Replace variables in YAML'
      - task: kubernetes@1
        displayName: "Apply Deployment YAML"
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceEndpoint: $(kubernetesServiceEndpoint)
          namespace: $(kubernetesNamespace)
          command: apply
          arguments: -f $(System.DefaultWorkingDirectory)/$(k8sPathName)